### ISSUE TITLE
Adding Couchdb to store data generate through smart contracts and query them

### ISSUE THREAD

**Issue by tpasquet** [IBM/todo-list-fabricV1#4]
Hi ! 
I'm trying to add CouchDB to make rich queries through my smart-contract. 
I tried to modify the docker-compose-networksetup.yaml but i  then have some issues when i want to execute create-channel.js/join-channel.js.

Do you know how to do it ? Is there anything else to change except the docker-compose file ? 
Thanks by advance ! 
:)

**Comment by ishangulhane** [comment]
Hi, 

Can you provide more information on the steps you have taken and the issues you are facing while executing the create-channel.js/join-channel.js

Thanks!

**Comment by tpasquet** [comment]
I performed all the tutorial without couchDB, i create and join my channel, i install and instantiate my chaincode, and run the app.
Now, i make changes on the docker-compose-networksetup.yaml, here it is :

[docker-compose-network.zip](https://github.com/IBM/todo-list-fabricV1/files/1086190/docker-compose-network.zip)

Create-channel.js works, but join-channel.js gives me this error :

![error_join_channel](https://user-images.githubusercontent.com/15611165/27303678-e1f8a4ca-553b-11e7-818e-98d09f90ba16.png)

**Comment by tpasquet** [comment]
The problem comes from the two lines i added for each peer (peer0, peer1, peer2 and peer3) : 
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
But i don't know why...

**Comment by ishangulhane** [comment]
Hi,

I have made some changes to docker-compose-networksetup.yaml file. join-channel.js is working fine for me.
[docker-compose-network.zip](https://github.com/IBM/todo-list-fabricV1/files/1086351/docker-compose-network.zip)
<img width="1596" alt="screen shot 2017-06-19 at 2 03 40 pm" src="https://user-images.githubusercontent.com/26394621/27306043-0854f0a8-54f9-11e7-9abb-46a0cdb3cec8.png">
