### ISSUE TITLE
query response is empty when trying to log in

### ISSUE THREAD

**Issue by BechirHouas** [IBM/todo-list-fabricV1#6]
info: Fetching EVERYTHING...
debug: [fcw] Querying Chaincode: account_read()
debug: [fcw] Sending query req chainId=mychannel, chaincodeId=end2end, chaincodeVersion=v1, fcn=account_read, args=[krhoyt, abc123], txId=df379ff15a4a6339c9d581c619bf28cdba6bc478a2264f58da636e3e4ea67fc0
debug: [fcw] Peer 0 len 4
debug: [fcw] Peer 0 type object
debug: [fcw] Query response is empty undefined
debug: Results from query_function invoke_cc: 
debug: { parsed: null,
  peers_agree: true,
  raw_peer_payloads: [ 'null' ] }
debug: null
debug: Query parameters : [object Object]

**Comment by LennartFr** [comment]
I have gone thru the entire repo step by step without getting any errors. When I log in to the application and enter the user id and password nothing happens, I do not get into the application. And in the console window I get the following message:

Any idea how to fix this issue?
`
info: Fetching EVERYTHING...
debug: [fcw] Querying Chaincode: account_browse()
debug: [fcw] Sending query req chainId=mychannel, chaincodeId=end2end, chaincodeVersion=v1, fcn=account_browse, args=[], txId=6c68872f0b748c22a69a005847aed398fb3819e496189cb86fdd74c3bd2d3722
error: [Peer.js]: GRPC client got an error response from the peer "grpc://localhost:7051". Error: failed to obtain cds for end2end - transaction not found end2end/mychannel
    at /Users/arnelennartfrantzell/Blockchain/todolist/todo-list-fabricV1-master/todo-list-fabric-server/node_modules/grpc/src/node/src/client.js:434:17
error: [Chain.js]: Chain-sendPeersProposal - Promise is rejected: Error: failed to obtain cds for end2end - transaction not found end2end/mychannel
    at /Users/arnelennartfrantzell/Blockchain/todolist/todo-list-fabricV1-master/todo-list-fabric-server/node_modules/grpc/src/node/src/client.js:434:17
debug: [fcw] Peer 0 len 81
error: [fcw] query resp looks like an error string Error: failed to obtain cds for end2end - transaction not found end2end/mychannel
debug: [fcw] Query response is empty undefined
debug: Results from query_function invoke_cc: 
debug: { parsed: null,
  peers_agree: true,
  raw_peer_payloads: [ 'Error: failed to obtain cds for end2end - transaction not found end2end/mychannel' ] }
debug: null
`

**Comment by ishangulhane** [comment]
@BechirHouas The login dialog contains an IBM logo. Alt+Click on that logo to preload data into the blockchain. The only indication that this operation has been completed is a transaction ID in the developer console.
