### ISSUE TITLE
Error: instantiate-chaincode.js 

### ISSUE THREAD

**Issue by GoodFaithParadigm8** [IBM/todo-list-fabricV1#8]
Env:

Go: v1.8.3
Node: v6.10.3
Docker: v17.09.0-ce
Docker-Compose: v1.17.0

Expecation: node test/integration/e2e/instantiate-chaincode.js

Result Error: 

`RPC client got an error response from the peer "grpc://localhost:7051". Error: Error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "can't load package: package github.com/example_cc: no buildable Go source files in /chaincode/input/src/github.com/example_cc
"
    at /home/goodfaith/fabric-sdk-node/node_modules/grpc/src/node/src/client.js:434:17`

Created the directory /chaincode/input... and copied the src with the rest of the file directory. Got the same error message.

Error:

` Returning a new winston logger with default configurations
TAP version 13
# 

***** End-to-end flow: instantiate chaincode *****
info: [Peer.js]: Peer.const - url: grpc://localhost:7051 options  grpc.ssl_target_name_override=peer0, grpc.default_authority=peer0
info: [Peer.js]: Peer.const - url: grpc://localhost:8051 options  grpc.ssl_target_name_override=peer2, grpc.default_authority=peer2
info: [crypto_ecdsa_aes]: This class requires a CryptoKeyStore to save keys, using the store: {"opts":{"path":"/home/goodfaith/.hfc-key-store"}}
info: [Client.js]: Successfully loaded user "admin" from local key value store
ok 1 Successfully loaded member from persistence
ok 2 Successfully enrolled user 'admin'
error: [Peer.js]: GRPC client got an error response from the peer "grpc://localhost:8051". Error: Error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "can't load package: package github.com/example_cc: no buildable Go source files in /chaincode/input/src/github.com/example_cc
"
    at /home/goodfaith/fabric-sdk-node/node_modules/grpc/src/node/src/client.js:434:17
error: [Chain.js]: Chain-sendPeersProposal - Promise is rejected: Error: Error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "can't load package: package github.com/example_cc: no buildable Go source files in /chaincode/input/src/github.com/example_cc
"
    at /home/goodfaith/fabric-sdk-node/node_modules/grpc/src/node/src/client.js:434:17
error: [Peer.js]: GRPC client got an error response from the peer "grpc://localhost:7051". Error: Error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "can't load package: package github.com/example_cc: no buildable Go source files in /chaincode/input/src/github.com/example_cc
"
    at /home/goodfaith/fabric-sdk-node/node_modules/grpc/src/node/src/client.js:434:17
error: [Chain.js]: Chain-sendPeersProposal - Promise is rejected: Error: Error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "can't load package: package github.com/example_cc: no buildable Go source files in /chaincode/input/src/github.com/example_cc
"
    at /home/goodfaith/fabric-sdk-node/node_modules/grpc/src/node/src/client.js:434:17
error: [install-chaincode]: instantiate proposal was bad
error: [install-chaincode]: instantiate proposal was bad
not ok 3 Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting...
  ---
    operator: fail
    at: hfc.newDefaultKeyValueStore.then.then.then.then (/home/goodfaith/fabric-sdk-node/input/integration/e2e/instantiate-chaincode.js:228:6)
    stack: |-
      Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting...
          at Test.assert [as _assert] (/home/goodfaith/fabric-sdk-node/node_modules/tape/lib/test.js:212:54)
          at Test.bound [as _assert] (/home/goodfaith/fabric-sdk-node/node_modules/tape/lib/test.js:64:32)
          at Test.fail (/home/goodfaith/fabric-sdk-node/node_modules/tape/lib/test.js:277:10)
          at Test.bound [as fail] (/home/goodfaith/fabric-sdk-node/node_modules/tape/lib/test.js:64:32)
          at hfc.newDefaultKeyValueStore.then.then.then.then (/home/goodfaith/fabric-sdk-node/input/integration/e2e/instantiate-chaincode.js:228:6)
          at process._tickCallback (internal/process/next_tick.js:109:7)
  ...
not ok 4 Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting... at hfc.newDefaultKeyValueStore.then.then.then.then (/home/goodfaith/fabric-sdk-node/input/integration/e2e/instantiate-chaincode.js:229:10) at process._tickCallback (internal/process/next_tick.js:109:7)
  ---
    operator: fail
    at: hfc.newDefaultKeyValueStore.then.then.then.then.then (/home/goodfaith/fabric-sdk-node/input/integration/e2e/instantiate-chaincode.js:246:5)
    stack: |-
      Error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting...
          at hfc.newDefaultKeyValueStore.then.then.then.then (/home/goodfaith/fabric-sdk-node/input/integration/e2e/instantiate-chaincode.js:229:10)
          at process._tickCallback (internal/process/next_tick.js:109:7)
          at Test.assert [as _assert] (/home/goodfaith/fabric-sdk-node/node_modules/tape/lib/test.js:212:54)
          at Test.bound [as _assert] (/home/goodfaith/fabric-sdk-node/node_modules/tape/lib/test.js:64:32)
          at Test.fail (/home/goodfaith/fabric-sdk-node/node_modules/tape/lib/test.js:277:10)
          at Test.bound [as fail] (/home/goodfaith/fabric-sdk-node/node_modules/tape/lib/test.js:64:32)
          at hfc.newDefaultKeyValueStore.then.then.then.then.then (/home/goodfaith/fabric-sdk-node/input/integration/e2e/instantiate-chaincode.js:246:5)
          at process._tickCallback (internal/process/next_tick.js:109:7)
  ...
info: [install-chaincode]: Disconnecting the event hub
info: [install-chaincode]: Disconnecting the event hub
not ok 5 Error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting... at hfc.newDefaultKeyValueStore.then.then.then.then (/home/goodfaith/fabric-sdk-node/input/integration/e2e/instantiate-chaincode.js:229:10) at process._tickCallback (internal/process/next_tick.js:109:7)
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting...
    at hfc.newDefaultKeyValueStore.then.then.then.then (/home/goodfaith/fabric-sdk-node/input/integration/e2e/instantiate-chaincode.js:229:10)
    at process._tickCallback (internal/process/next_tick.js:109:7)]
    at: Test.onetime (/home/goodfaith/fabric-sdk-node/node_modules/onetime/index.js:22:12)
    stack: |-
      Error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting...
          at hfc.newDefaultKeyValueStore.then.then.then.then (/home/goodfaith/fabric-sdk-node/input/integration/e2e/instantiate-chaincode.js:229:10)
          at process._tickCallback (internal/process/next_tick.js:109:7)
          at hfc.newDefaultKeyValueStore.then.then.then.then.then (/home/goodfaith/fabric-sdk-node/input/integration/e2e/instantiate-chaincode.js:247:9)
          at process._tickCallback (internal/process/next_tick.js:109:7)
  ...

1..5
# tests 5
# pass  2
# fail  3`

**Comment by ishangulhane** [comment]
@GoodFaithParadigm8  There is no chaincode present to inst instantiate chaincode. You missed the instruction to copy the chaincode in step 1 ```cp todo-list-fabric-server/chaincode/* fabric-sdk-node/test/fixtures/src/github.com/example_cc/```. Please try again.

**Comment by deepanair** [comment]
Hello - When I try to run the install-chaincode.js script after copying the files, I get the following error:
error: [Peer.js]: GRPC client got an error response from the peer "grpc://localhost:7051". Error: Illegal file detected in payload: "src\github.com\example_cc\account.go"
    at C:\Users\pilla\to-do\todo-list-fabricV1\fabric-sdk-node\node_modules\grpc\src\client.js:554:15
error: [Chain.js]: Chain-sendPeersProposal - Promise is rejected: Error: Illegal file detected in payload: "src\github.com\example_cc\account.go"
    at C:\Users\pilla\to-do\todo-list-fabricV1\fabric-sdk-node\node_modules\grpc\src\client.js:554:15
error: [Peer.js]: GRPC client got an error response from the peer "grpc://localhost:7056". Error: Illegal file detected in payload: "src\github.com\example_cc\account.go"
    at C:\Users\pilla\to-do\todo-list-fabricV1\fabric-sdk-node\node_modules\grpc\src\client.js:554:15
error: [Chain.js]: Chain-sendPeersProposal - Promise is rejected: Error: Illegal file detected in payload: "src\github.com\example_cc\account.go"
    at C:\Users\pilla\to-do\todo-list-fabricV1\fabric-sdk-node\node_modules\grpc\src\client.js:554:15
error: [install-chaincode]: install proposal

**Comment by ljbennett62** [comment]
@ishangulhane - also this...tx
